<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Company>USSBD</Company>

    <AssemblyName>DeployKeyGitClient</AssemblyName>
    <RootNamespace>DeployKeyGitClient</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DeployKeyGitClientAgent\**\*.cs" />
    <EmbeddedResource Remove="DeployKeyGitClientAgent\**\*.resx" />
    <None Remove="DeployKeyGitClientAgent\**\*" />
  </ItemGroup>
</Project>
